INSERT INTO Book (title, author, is_available, borrowed_by_user_id, borrow_count, library_user_id)
VALUES ('Spring Boot in Action', 'Craig Walls', TRUE, NULL, 0, NULL),
       ('Effective Java', 'Joshua Bloch', TRUE, NULL, 0, NULL),
       ('Clean Code', 'Robert C. Martin', TRUE, NULL, 0, NULL),
       ('Java Concurrency in Practice', 'Brian Goetz', TRUE, NULL, 0, NULL),
       ('Head First Java', 'Kathy Sierra', TRUE, NULL, 0, NULL),
       ('Design Patterns', 'Erich Gamma', TRUE, NULL, 0, NULL),
       ('Refactoring', 'Martin Fowler', TRUE, NULL, 0, NULL),
       ('Microservices Patterns', 'Chris Richardson', TRUE, NULL, 0, NULL),
       ('Java: The Complete Reference', 'Herbert Schildt', TRUE, NULL, 0, NULL),
       ('Thinking in Java', 'Bruce Eckel', TRUE, NULL, 0, NULL),
       ('Python Crash Course', 'Eric Matthes', TRUE, NULL, 0, NULL),
       ('Automate the Boring Stuff with Python', 'Al Sweigart', TRUE, NULL, 0, NULL),
       ('Fluent Python', 'Luciano Ramalho', TRUE, NULL, 0, NULL),
       ('The Pragmatic Programmer', 'Andrew Hunt', TRUE, NULL, 0, NULL),
       ('You Don’t Know JS', 'Kyle Simpson', TRUE, NULL, 0, NULL),
       ('JavaScript: The Good Parts', 'Douglas Crockford', TRUE, NULL, 0, NULL),
       ('Eloquent JavaScript', 'Marijn Haverbeke', TRUE, NULL, 0, NULL),
       ('The Mythical Man-Month', 'Frederick P. Brooks Jr.', TRUE, NULL, 0, NULL),
       ('Code Complete', 'Steve McConnell', TRUE, NULL, 0, NULL),
       ('Deep Work', 'Cal Newport', TRUE, NULL, 0, NULL),
       ('Soft Skills', 'John Sonmez', TRUE, NULL, 0, NULL),
       ('Algorithms', 'Robert Sedgewick', TRUE, NULL, 0, NULL),
       ('Introduction to the Theory of Computation', 'Michael Sipser', TRUE, NULL, 0, NULL),
       ('Data Structures and Algorithm Analysis', 'Mark Allen Weiss', TRUE, NULL, 0, NULL),
       ('Database Systems', 'Thomas Connolly', TRUE, NULL, 0, NULL),
       ('Operating System Concepts', 'Abraham Silberschatz', TRUE, NULL, 0, NULL),
       ('Computer Networks', 'Andrew S. Tanenbaum', TRUE, NULL, 0, NULL),
       ('Cybersecurity and Cyberwar', 'P.W. Singer', TRUE, NULL, 0, NULL),
       ('Cryptography and Network Security', 'William Stallings', TRUE, NULL, 0, NULL),
       ('Artificial Intelligence: A Modern Approach', 'Stuart Russell', TRUE, NULL, 0, NULL),
       ('Machine Learning', 'Tom M. Mitchell', TRUE, NULL, 0, NULL),
       ('Deep Learning', 'Ian Goodfellow', TRUE, NULL, 0, NULL),
       ('Pattern Recognition and Machine Learning', 'Christopher Bishop', TRUE, NULL, 0, NULL),
       ('Computer Vision: Algorithms and Applications', 'Richard Szeliski', TRUE, NULL, 0, NULL),
       ('Reinforcement Learning', 'Richard S. Sutton', TRUE, NULL, 0, NULL),
       ('Programming Pearls', 'Jon Bentley', TRUE, NULL, 0, NULL),
       ('Code', 'Charles Petzold', TRUE, NULL, 0, NULL),
       ('The Art of Computer Programming', 'Donald Knuth', TRUE, NULL, 0, NULL),
       ('How to Solve It', 'G. Polya', TRUE, NULL, 0, NULL),
       ('Structure and Interpretation of Computer Programs', 'Harold Abelson', TRUE, NULL, 0, NULL),
       ('Domain-Driven Design', 'Eric Evans', TRUE, NULL, 0, NULL),
       ('Software Architecture in Practice', 'Len Bass', TRUE, NULL, 0, NULL),
       ('The Phoenix Project', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Site Reliability Engineering', 'Betsy Beyer', TRUE, NULL, 0, NULL),
       ('The Unicorn Project', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Working Effectively with Legacy Code', 'Michael Feathers', TRUE, NULL, 0, NULL),
       ('Continuous Delivery', 'Jez Humble', TRUE, NULL, 0, NULL),
       ('An Elegant Puzzle', 'Will Larson', TRUE, NULL, 0, NULL),
       ('Managing Humans', 'Michael Lopp', TRUE, NULL, 0, NULL),
       ('The Effective Engineer', 'Edmond Lau', TRUE, NULL, 0, NULL),
       ('Accelerate', 'Nicole Forsgren', TRUE, NULL, 0, NULL),
       ('Release It!', 'Michael Nygard', TRUE, NULL, 0, NULL),
       ('Production-Ready Microservices', 'Susan Fowler', TRUE, NULL, 0, NULL),
       ('The DevOps Handbook', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Security Engineering', 'Ross Anderson', TRUE, NULL, 0, NULL),
       ('Hacking: The Art of Exploitation', 'Jon Erickson', TRUE, NULL, 0, NULL),
       ('Compilers: Principles, Techniques, and Tools', 'Alfred V. Aho', TRUE, NULL, 0, NULL),
       ('Web Application Security', 'Andrew Hoffman', TRUE, NULL, 0, NULL),
       ('The Cathedral and the Bazaar', 'Eric S. Raymond', TRUE, NULL, 0, NULL),
       ('The Pragmatic Programmer 2nd Edition', 'David Thomas', TRUE, NULL, 0, NULL),
       ('Mastering Regular Expressions', 'Jeffrey E.F. Friedl', TRUE, NULL, 0, NULL),
       ('Java Performance', 'Scott Oaks', TRUE, NULL, 0, NULL),
       ('High Performance MySQL', 'Baron Schwartz', TRUE, NULL, 0, NULL),
       ('PostgreSQL: Up and Running', 'Regina O. Obe', TRUE, NULL, 0, NULL),
       ('MongoDB: The Definitive Guide', 'Kristina Chodorow', TRUE, NULL, 0, NULL),
       ('Redis Essentials', 'Maxwell Dayvson Da Silva', TRUE, NULL, 0, NULL),
       ('Kubernetes Up & Running', 'Kelsey Hightower', TRUE, NULL, 0, NULL),
       ('Cloud Native Patterns', 'Cornelia Davis', TRUE, NULL, 0, NULL),
       ('Building Microservices', 'Sam Newman', TRUE, NULL, 0, NULL),
       ('Software Engineering at Google', 'Titus Winters', TRUE, NULL, 0, NULL),
       ('Refactoring UI', 'Adam Wathan', TRUE, NULL, 0, NULL),
       ('UX for Lean Startups', 'Laura Klein', TRUE, NULL, 0, NULL),
       ('Emotional Design', 'Don Norman', TRUE, NULL, 0, NULL),
       ('Don’t Make Me Think', 'Steve Krug', TRUE, NULL, 0, NULL),
       ('Hooked', 'Nir Eyal', TRUE, NULL, 0, NULL),
       ('The Lean Startup', 'Eric Ries', TRUE, NULL, 0, NULL),
       ('Zero to One', 'Peter Thiel', TRUE, NULL, 0, NULL),
       ('The Hard Thing About Hard Things', 'Ben Horowitz', TRUE, NULL, 0, NULL),
       ('Measure What Matters', 'John Doerr', TRUE, NULL, 0, NULL),
       ('The 4-Hour Workweek', 'Timothy Ferriss', TRUE, NULL, 0, NULL),
       ('Deep Learning for Coders', 'Jeremy Howard', TRUE, NULL, 0, NULL),
       ('Neural Networks and Deep Learning', 'Michael Nielsen', TRUE, NULL, 0, NULL),
       ('AI Superpowers', 'Kai-Fu Lee', TRUE, NULL, 0, NULL),
       ('Life 3.0', 'Max Tegmark', TRUE, NULL, 0, NULL),
       ('The Code Book', 'Simon Singh', TRUE, NULL, 0, NULL),
       ('Grokking Algorithms', 'Aditya Bhargava', TRUE, NULL, 0, NULL),
       ('Essential Scrum', 'Kenneth S. Rubin', TRUE, NULL, 0, NULL),
       ('The Culture Code', 'Daniel Coyle', TRUE, NULL, 0, NULL),
       ('Atomic Habits', 'James Clear', TRUE, NULL, 0, NULL),
       ('The Power of Habit', 'Charles Duhigg', TRUE, NULL, 0, NULL),
       ('Thinking, Fast and Slow', 'Daniel Kahneman', TRUE, NULL, 0, NULL),
       ('Predictably Irrational', 'Dan Ariely', TRUE, NULL, 0, NULL),
       ('Mindset', 'Carol S. Dweck', TRUE, NULL, 0, NULL),
       ('The Psychology of Money', 'Morgan Housel', TRUE, NULL, 0, NULL),
       ('Rich Dad Poor Dad', 'Robert Kiyosaki', TRUE, NULL, 0, NULL),
       ('Principles', 'Ray Dalio', TRUE, NULL, 0, NULL),
       ('Sapiens', 'Yuval Noah Harari', TRUE, NULL, 0, NULL),
       ('Homo Deus', 'Yuval Noah Harari', TRUE, NULL, 0, NULL),
       ('The Selfish Gene', 'Richard Dawkins', TRUE, NULL, 0, NULL),
       ('Brief Answers to the Big Questions', 'Stephen Hawking', TRUE, NULL, 0, NULL),
       ('The Elegant Universe', 'Brian Greene', TRUE, NULL, 0, NULL),
       ('A Brief History of Time', 'Stephen Hawking', TRUE, NULL, 0, NULL),
       ('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', TRUE, NULL, 0, NULL),
       ('Why We Sleep', 'Matthew Walker', TRUE, NULL, 0, NULL),
       ('The Body', 'Bill Bryson', TRUE, NULL, 0, NULL),
       ('The Gene', 'Siddhartha Mukherjee', TRUE, NULL, 0, NULL),
       ('Bad Blood', 'John Carreyrou', TRUE, NULL, 0, NULL),
       ('The Black Swan', 'Nassim Nicholas Taleb', TRUE, NULL, 0, NULL),
       ('Antifragile', 'Nassim Nicholas Taleb', TRUE, NULL, 0, NULL),
       ('The Hobbit', 'J.R.R. Tolkien', TRUE, NULL, 0, NULL),
       ('The Lord of the Rings', 'J.R.R. Tolkien', TRUE, NULL, 0, NULL),
       ('The Silmarillion', 'J.R.R. Tolkien', TRUE, NULL, 0, NULL),
       ('A Game of Thrones', 'George R.R. Martin', TRUE, NULL, 0, NULL),
       ('A Clash of Kings', 'George R.R. Martin', TRUE, NULL, 0, NULL),
       ('A Storm of Swords', 'George R.R. Martin', TRUE, NULL, 0, NULL),
       ('The Name of the Wind', 'Patrick Rothfuss', TRUE, NULL, 0, NULL),
       ('The Wise Man’s Fear', 'Patrick Rothfuss', TRUE, NULL, 0, NULL),
       ('Mistborn: The Final Empire', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('The Well of Ascension', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('The Hero of Ages', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('The Way of Kings', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('Words of Radiance', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('The Final Empire', 'Brandon Sanderson', TRUE, NULL, 0, NULL),
       ('The Lies of Locke Lamora', 'Scott Lynch', TRUE, NULL, 0, NULL),
       ('Red Seas Under Red Skies', 'Scott Lynch', TRUE, NULL, 0, NULL),
       ('The Republic of Thieves', 'Scott Lynch', TRUE, NULL, 0, NULL),
       ('The Blade Itself', 'Joe Abercrombie', TRUE, NULL, 0, NULL),
       ('Before They Are Hanged', 'Joe Abercrombie', TRUE, NULL, 0, NULL),
       ('Last Argument of Kings', 'Joe Abercrombie', TRUE, NULL, 0, NULL),
       ('The Fifth Season', 'N.K. Jemisin', TRUE, NULL, 0, NULL),
       ('The Obelisk Gate', 'N.K. Jemisin', TRUE, NULL, 0, NULL),
       ('The Stone Sky', 'N.K. Jemisin', TRUE, NULL, 0, NULL),
       ('Good Omens', 'Terry Pratchett & Neil Gaiman', TRUE, NULL, 0, NULL),
       ('American Gods', 'Neil Gaiman', TRUE, NULL, 0, NULL),
       ('Neverwhere', 'Neil Gaiman', TRUE, NULL, 0, NULL),
       ('Coraline', 'Neil Gaiman', TRUE, NULL, 0, NULL),
       ('The Ocean at the End of the Lane', 'Neil Gaiman', TRUE, NULL, 0, NULL),
       ('The Colour of Magic', 'Terry Pratchett', TRUE, NULL, 0, NULL),
       ('Guards! Guards!', 'Terry Pratchett', TRUE, NULL, 0, NULL),
       ('Mort', 'Terry Pratchett', TRUE, NULL, 0, NULL),
       ('Small Gods', 'Terry Pratchett', TRUE, NULL, 0, NULL),
       ('Night Watch', 'Terry Pratchett', TRUE, NULL, 0, NULL),
       ('The Left Hand of Darkness', 'Ursula K. Le Guin', TRUE, NULL, 0, NULL),
       ('A Wizard of Earthsea', 'Ursula K. Le Guin', TRUE, NULL, 0, NULL),
       ('The Tombs of Atuan', 'Ursula K. Le Guin', TRUE, NULL, 0, NULL),
       ('The Farthest Shore', 'Ursula K. Le Guin', TRUE, NULL, 0, NULL),
       ('Assassin’s Apprentice', 'Robin Hobb', TRUE, NULL, 0, NULL),
       ('Royal Assassin', 'Robin Hobb', TRUE, NULL, 0, NULL),
       ('Assassin’s Quest', 'Robin Hobb', TRUE, NULL, 0, NULL),
       ('The Black Prism', 'Brent Weeks', TRUE, NULL, 0, NULL),
       ('The Blinding Knife', 'Brent Weeks', TRUE, NULL, 0, NULL),
       ('The Broken Eye', 'Brent Weeks', TRUE, NULL, 0, NULL),
       ('The Burning White', 'Brent Weeks', TRUE, NULL, 0, NULL),
       ('Dune', 'Frank Herbert', TRUE, NULL, 0, NULL),
       ('Children of Dune', 'Frank Herbert', TRUE, NULL, 0, NULL),
       ('God Emperor of Dune', 'Frank Herbert', TRUE, NULL, 0, NULL),
       ('Hyperion', 'Dan Simmons', TRUE, NULL, 0, NULL),
       ('The Fall of Hyperion', 'Dan Simmons', TRUE, NULL, 0, NULL);