INSERT INTO Book (title, author, is_available, borrowed_by_user_id, borrow_count, library_user_id)
VALUES ('Spring Boot in Action', 'Craig Walls', TRUE, NULL, 0, NULL),
       ('Effective Java', 'Joshua Bloch', TRUE, NULL, 0, NULL),
       ('Clean Code', 'Robert C. Martin', TRUE, NULL, 0, NULL),
       ('Java Concurrency in Practice', 'Brian Goetz', TRUE, NULL, 0, NULL),
       ('Head First Java', 'Kathy Sierra', TRUE, NULL, 0, NULL),
       ('Design Patterns', 'Erich Gamma', TRUE, NULL, 0, NULL),
       ('Refactoring', 'Martin Fowler', TRUE, NULL, 0, NULL),
       ('Microservices Patterns', 'Chris Richardson', TRUE, NULL, 0, NULL),
       ('Java: The Complete Reference', 'Herbert Schildt', TRUE, NULL, 0, NULL),
       ('Thinking in Java', 'Bruce Eckel', TRUE, NULL, 0, NULL),
       ('Python Crash Course', 'Eric Matthes', TRUE, NULL, 0, NULL),
       ('Automate the Boring Stuff with Python', 'Al Sweigart', TRUE, NULL, 0, NULL),
       ('Fluent Python', 'Luciano Ramalho', TRUE, NULL, 0, NULL),
       ('The Pragmatic Programmer', 'Andrew Hunt', TRUE, NULL, 0, NULL),
       ('You Don’t Know JS', 'Kyle Simpson', TRUE, NULL, 0, NULL),
       ('JavaScript: The Good Parts', 'Douglas Crockford', TRUE, NULL, 0, NULL),
       ('Eloquent JavaScript', 'Marijn Haverbeke', TRUE, NULL, 0, NULL),
       ('The Mythical Man-Month', 'Frederick P. Brooks Jr.', TRUE, NULL, 0, NULL),
       ('Code Complete', 'Steve McConnell', TRUE, NULL, 0, NULL),
       ('Deep Work', 'Cal Newport', TRUE, NULL, 0, NULL),
       ('Soft Skills', 'John Sonmez', TRUE, NULL, 0, NULL),
       ('Algorithms', 'Robert Sedgewick', TRUE, NULL, 0, NULL),
       ('Introduction to the Theory of Computation', 'Michael Sipser', TRUE, NULL, 0, NULL),
       ('Data Structures and Algorithm Analysis', 'Mark Allen Weiss', TRUE, NULL, 0, NULL),
       ('Database Systems', 'Thomas Connolly', TRUE, NULL, 0, NULL),
       ('Operating System Concepts', 'Abraham Silberschatz', TRUE, NULL, 0, NULL),
       ('Computer Networks', 'Andrew S. Tanenbaum', TRUE, NULL, 0, NULL),
       ('Cybersecurity and Cyberwar', 'P.W. Singer', TRUE, NULL, 0, NULL),
       ('Cryptography and Network Security', 'William Stallings', TRUE, NULL, 0, NULL),
       ('Artificial Intelligence: A Modern Approach', 'Stuart Russell', TRUE, NULL, 0, NULL),
       ('Machine Learning', 'Tom M. Mitchell', TRUE, NULL, 0, NULL),
       ('Deep Learning', 'Ian Goodfellow', TRUE, NULL, 0, NULL),
       ('Pattern Recognition and Machine Learning', 'Christopher Bishop', TRUE, NULL, 0, NULL),
       ('Computer Vision: Algorithms and Applications', 'Richard Szeliski', TRUE, NULL, 0, NULL),
       ('Reinforcement Learning', 'Richard S. Sutton', TRUE, NULL, 0, NULL),
       ('Programming Pearls', 'Jon Bentley', TRUE, NULL, 0, NULL),
       ('Code', 'Charles Petzold', TRUE, NULL, 0, NULL),
       ('The Art of Computer Programming', 'Donald Knuth', TRUE, NULL, 0, NULL),
       ('How to Solve It', 'G. Polya', TRUE, NULL, 0, NULL),
       ('Structure and Interpretation of Computer Programs', 'Harold Abelson', TRUE, NULL, 0, NULL),
       ('Domain-Driven Design', 'Eric Evans', TRUE, NULL, 0, NULL),
       ('Software Architecture in Practice', 'Len Bass', TRUE, NULL, 0, NULL),
       ('The Phoenix Project', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Site Reliability Engineering', 'Betsy Beyer', TRUE, NULL, 0, NULL),
       ('The Unicorn Project', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Working Effectively with Legacy Code', 'Michael Feathers', TRUE, NULL, 0, NULL),
       ('Continuous Delivery', 'Jez Humble', TRUE, NULL, 0, NULL),
       ('An Elegant Puzzle', 'Will Larson', TRUE, NULL, 0, NULL),
       ('Managing Humans', 'Michael Lopp', TRUE, NULL, 0, NULL),
       ('The Effective Engineer', 'Edmond Lau', TRUE, NULL, 0, NULL),
       ('Accelerate', 'Nicole Forsgren', TRUE, NULL, 0, NULL),
       ('Release It!', 'Michael Nygard', TRUE, NULL, 0, NULL),
       ('Production-Ready Microservices', 'Susan Fowler', TRUE, NULL, 0, NULL),
       ('The DevOps Handbook', 'Gene Kim', TRUE, NULL, 0, NULL),
       ('Security Engineering', 'Ross Anderson', TRUE, NULL, 0, NULL),
       ('Hacking: The Art of Exploitation', 'Jon Erickson', TRUE, NULL, 0, NULL),
       ('Compilers: Principles, Techniques, and Tools', 'Alfred V. Aho', TRUE, NULL, 0, NULL),
       ('Web Application Security', 'Andrew Hoffman', TRUE, NULL, 0, NULL),
       ('The Cathedral and the Bazaar', 'Eric S. Raymond', TRUE, NULL, 0, NULL);